version: '3.7'
services:

  #Laravel API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: dbemployees
      DB_USERNAME: employees
      DB_PASSWORD: employees
    ports:
      - 8000:8000
    volumes:
      - ./server:/var/www/
    depends_on:
      - db
    networks:
      - app

  #Vue FrontEnd
  vue:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /var/www/vue
    tty: true
    ports:
      - 3002:3002
    volumes:
      - ./client:/var/www/vue
    depends_on:
      - api
    networks:
      - app

  #DataBase PosGresQL
  db:
    image: postgres:14.1-alpine
    container_name: db
    #command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'employees'
      POSTGRES_PASSWORD: 'employees'
      POSTGRES_DB: 'dbemployees'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app

#Data Persist
volumes:
  dbdata:
    driver: local

networks:
  app:
    driver: bridge